### ISSUE TITLE
"Not a valid identifier"

### ISSUE THREAD

**Issue by UnregisteredUsername** [radumirea/ncmpcpp-with-cover-art#1]
I've been trying to set this up whilst following your guide on radumirea.com however when i run it I'm met with the error `/home/<user>/.local/lib/python3.9/site-packages/ueberzug/lib/lib.sh: line 6: 'String::trim': not a valid identifier` where the album art would go.
I'm using the fish shell on Gentoo Linux with the 5.10.49-gentoo-r1 kernel.
![2021-07-24-163905_757x590_scrot](https://user-images.githubusercontent.com/77406949/126871949-93ee7974-d22f-43d0-bb62-b6918d44dab3.png)

**Comment by radumirea** [comment]
Hi. Did you change the `tsession` file to run `cover.sh` explicitly using `sh`? If so, change it with `bash` since ueberzug scripts are using bashisms and will not work otherwise.

**Comment by UnregisteredUsername** [comment]
I did. After changing it to bash the error disappeared, I can however not get the terminal to render the album art. Running it in a bash shell produces an identical result.
![2021-07-29-100135_564x532_scrot](https://user-images.githubusercontent.com/77406949/127454704-60c46a59-94a2-4c53-bf75-55c806166c50.png)

**Comment by radumirea** [comment]
Does your directory containing the song also contain an album art? If not, do you have an image named ```default_cover.png``` in ```~/.ncmpcpp/```?  
Since your default shell is not bash, you should call all scripts with bash explicitly (all you have left is the command from ```execute_on_song_change``` in ```catalog.conf```).

**Comment by UnregisteredUsername** [comment]
Every album directory has a file named `cover.jpg` containing the album art. I also have the `default_cover.png` file from this exact repo.
I did not initially use `catalog.conf` or `visualizer.conf` and instead just called both to my standard config. Adding those two files and editing my `catalog.conf` and `tsession` to use it did not  fix the issue.
I was able to get the `default_cover.png` image to show when i realized that I hadn't compiled ImageMagick.

**Comment by UnregisteredUsername** [comment]
Besides the inability to show the actual albums cover art, I am now also met with the two errors ~~`MPD: error Connection refused`~~ and `find: ' ': No such file or directory` as seen in the screenshot below. Everything seems to work normally though. 
![2021-07-31-150842_1042x553_scrot](https://user-images.githubusercontent.com/77406949/127741034-cce56a0e-f744-42e4-b047-c00d380c1a3c.png)

**Comment by UnregisteredUsername** [comment]
~~The `MPD: error Connection refused` error seems to be related to the `execute_on_song_change` in my config as it disappears when i ommit it.~~
Turns out MPC is what invokes `MPD: error Connection refused`. I'll take another look at my config.

**Comment by radumirea** [comment]
Forgot to mention in the tutorial that you need to export the path to your music directory into an environment variable called ```MUSIC_DIR``` and have```mpc``` installed. Will update the steps.  
Also, I see that the image size is a bit too big for your screen. Try changing the ```COVER_SIZE``` from ```cover_obs.sh```.

**Comment by UnregisteredUsername** [comment]
Turns out it was just a simple port config issue.
After setting the environment variable it successfully found the album art, however the placement seem to be more or less random in my experience.
![2021-08-01-210618_1391x1248_scrot](https://user-images.githubusercontent.com/77406949/127782534-274dd76d-fc3b-42a8-830b-5e1221eb9256.png)

**Comment by radumirea** [comment]
Looks like you changed the ```x``` and ```y``` values from the ```add_cover``` function in ```cover_.sh```. Those act like padding for the image.

**Comment by UnregisteredUsername** [comment]
I hadn't changed those values, however it seems that resizing the window when starting the script will make it place itself in the corner correctly.
Thank you for your generous help in this matter.
![2021-08-03-192716_1058x694_scrot](https://user-images.githubusercontent.com/77406949/128059563-9607b7bf-6903-4ec8-ab52-eddfaa01d7c7.png)
