### ISSUE TITLE
"No such file or directory" Error

### ISSUE THREAD

**Issue by muvment** [radumirea/ncmpcpp-with-cover-art#2]
Hi! First off thank you so much for sharing this config, found your guide on your website and now I have ncmpcpp looking great but using cava as visualizer instead of the inbuilt default one.
I'm currently using it with mopidy-mpd, not mpd, and ueberzug works fine, I had it installed previously already along with ytfzf and it displays the fallback `default_cover.png`. I'm running into an issue that I see has been referenced in the other closed one (https://github.com/radumirea/ncmpcpp-with-cover-art/issues/1#issuecomment-890346963), I get the`No such file or directory` error.
I also read your response (https://github.com/radumirea/ncmpcpp-with-cover-art/issues/1#issuecomment-890489801) and you mention what you also mentioned in your website, that you have to set the `MUSIC_DIR` environment variable, but there's no detailed steps as to how-to (forgive me, I'm not very knowledgeable, simply tinkering as a beginner with all of these things ).
How would you do that? My music dir is in the following path format `/home/username/Music`, with all the folders and sub-folders subsequently with their respective tracks and cover art. Also, most songs have the album art embedded into each track.
Noteworthy to mention I get the same error with ncmpcpp-ueberzug or other configs I've tried.

**Comment by radumirea** [comment]
Hi. 
In this case you could just paste the following in your ```.bashrc```:
```
export MUSIC_DIR="/home/username/Music"
```
And then reload it with:
```
. ~/.bashrc
```
Good point about the embedded images. I updated the script to support that.

**Comment by muvment** [comment]
Hi, thanks, just updated it! And also thank you for the fast response. Unfortunately, still nothing...
I exported the path to my `.bashrc`, reloaded it, and checked `env`, it shows up correctly, but still nada...
It's so strange, I can see album art perfectly with Mopidy's MusicBox-Webclient on my web browser, it loads and shows it without problem, so at least on Mopidy's side it's detecting it, I don't know, I must be missing something...

**Comment by radumirea** [comment]
Hi.
Did the error message change? Is it still ```find: ' ': No such file or directory``` or is it now showing a file path?
It may be helpful to manually run the lines from ```cover_obs.sh``` one by one while a song is playing to have a better view at the error message in case it's partially hidden by the music player.

**Comment by muvment** [comment]
Hi! When I run the `cover_obs.sh` separately I can see the full output as you mentioned, it was half cut-off while in the player, and it says `find: ‘/home/username/Music/file:///home/username/Music/albumname’: No such file or directory`, with %20 between each separate word of the title when there is more then one (e.g. Jazz%20Compilation). Something seems wrong there, is it supposed to query the music folder path like that twice, repeated? It seems like it's searching for the `MUSIC_DIR` within the `MUSIC_DIR`, no?
I could try and run the lines manually one by one, but unfortunately I'm not familiar with the syntax... What would be the lines to run?

**Comment by radumirea** [comment]
Seems that mopidy-mpd is handling file references differently compared to mpd.
Try changing this line:
```
file="$MUSIC_DIR/$(mpc --format %file% current)"
```
to this:
```
file=$(mpc --format %file% current | cut -d ':' -f 2 | sed 's/%20/ /g')
```
If this works, you don't need the ```MUSIC_DIR``` env variable anymore.

**Comment by muvment** [comment]
Great, it works! Finally... Thank you for having helped with this problem, so glad to see it now working as intended, can now fully enjoy using ncmpcpp again!
And it's recognizing the embedded art too, tested with a music folder with no cover art image and it was pulling it from the songs, no issues!
Going to mess around and test with your modification with ncmpcpp-ueberzug, see if I can get that one working too.
(It'd be nice if ncmpcpp/mopidy would include a section in their wiki linking both your project and others like ncmpcpp-ueberzug, I've seen many people commenting and asking for instructions of how to do it in several places...)

**Comment by muvment** [comment]
Whoops, just realized I could've closed the issue myself (sorry, I'm new to this)... Apologies for the hassle, and thanks again!
